### ISSUE TITLE
compare_client_version fails on suffixed client versions

### ISSUE THREAD

**Issue by ckamm** [owncloud/smashbox#142]
Currently the 2.1.1 beta reports itself as `2.1.1beta1`. The `compare_client_version()` check fails with

```
2016-01-19 09:25:09,211 - CRITICAL - dir_to_file - Exception occured: invalid literal for int() with base 10: '1beta1\n' 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 164, in worker_wrap
    f(step)
  File "/home/kamm/dev/woboq/smashbox/lib/owncloud/test_dirBecomesFile.py", line 23, in dir_to_file
    if compare_client_version('2.1.0', '<='):
  File "/home/kamm/dev/woboq/smashbox/python/smashbox/utilities/__init__.py", line 45, in compare_client_version
    return compare_version(compare_to, operator, version)
  File "/home/kamm/dev/woboq/smashbox/python/smashbox/utilities/__init__.py", line 62, in compare_version
    return versiontuple(version) <= versiontuple(compare_to)
  File "/home/kamm/dev/woboq/smashbox/python/smashbox/utilities/__init__.py", line 73, in versiontuple
    return tuple(map(int, (v.split("."))))
ValueError: invalid literal for int() with base 10: '1beta1\n'
```

The code already has special-case handling for the `git` suffix. Maybe it should just strip any suffix before making the comparison?

**Comment by nickvergessen** [comment]
Fixed by https://github.com/owncloud/smashbox/pull/144
