### ISSUE TITLE
Issue with delete_user_from_group

### ISSUE THREAD

**Issue by PVince81** [owncloud/smashbox#24]
From @jnfrmarks:

> I'm seeing something weird in the ownCloudWebDav.py code that I'm using with smashbox.  Specifically, the "delete_user_from_group" method has stopped working correctly.  When I try to remove a user from a group, I get back a 101, invalid group, error. If I run the same test against 8.0.0rc2, the test works.  The curl command works fine:
> `curl http://centos_admin:admin@REDACTED/owncloud/ocs/v1.php/cloud/users/user3/groups -d groupid="testgroup1"`
> The test I'm running is test_shareGroup.py, one I wrote.

**Comment by PVince81** [comment]
@jnfrmarks can you post your logs ?

The test_basicSync.py works for me but when running test_shareGroup.py I'm getting this for step 5:

```
********************************************************************************
(5) shareeTwo:  SHAREE TWO SYNCS AND VALIDATE FILES DO EXIST
********************************************************************************
2015-03-05 11:20:04,627 - INFO - shareeOne - running '/usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_shareGroup/shareeOne/ owncloud://test2:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_shareGroup/shareeOne-ocsync.step05.cnt000.log 2>&1'
2015-03-05 11:20:04,627 - INFO - shareeTwo - running '/usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_shareGroup/shareeTwo/ owncloud://test3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_shareGroup/shareeTwo-ocsync.step05.cnt000.log 2>&1'
2015-03-05 11:20:05,203 - INFO - shareeTwo - sync cmd is: /usr/bin/owncloudcmd --trust /home/vincent/work/smashdir/test_shareGroup/shareeTwo/ owncloud://test3:test@127.0.0.1/owncloud/remote.php/webdav/ >> /home/vincent/work/smashdir/test_shareGroup/shareeTwo-ocsync.step05.cnt000.log 2>&1
2015-03-05 11:20:05,203 - INFO - shareeTwo - sync finished: 0:00:00.576259
2015-03-05 11:20:05,203 - INFO - shareeTwo - running 'ls -lh /home/vincent/work/smashdir/test_shareGroup/shareeTwo'
2015-03-05 11:20:05,216 - INFO - shareeTwo - stdout: total 4.0K
-rw-r--r-- 1 vincent users 163 Mar  5 11:20 welcome.txt

2015-03-05 11:20:05,217 - INFO - shareeTwo - Checking that /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_SHARE.dat is present in local directory for Sharee Two
2015-03-05 11:20:05,217 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_SHARE.dat should exist
2015-03-05 11:20:05,217 - INFO - shareeTwo - Checking that /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_RESHARE.dat is present in local directory for Sharee Two
2015-03-05 11:20:05,217 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_RESHARE.dat should exist
2015-03-05 11:20:05,217 - INFO - shareeTwo - Checking that /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat is present in local directory for Sharee Two
2015-03-05 11:20:05,217 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat should exist
```

I don't see any errors in "shareeTwo-ocsync.step05.cnt000.log"

Is that what you were seeing ?

**Comment by PVince81** [comment]
This is when running against v8.0.0

**Comment by PVince81** [comment]
Getting the same error when run against v8.0.0RC2 :frowning:

**Comment by PVince81** [comment]
@jnfrmarks is "delete_user_from_group" a new method ? I cannot find it in ownCloudWebDAV.py on the "sharing-tests" branch.

**Comment by PVince81** [comment]
I don't see any changes in provisioning API between v8.0.0RC2 and v8.0.0. Could be something else.

If I manage to run the test with the same results locally I could bisect it (or I can help you bisect it if you like)

**Comment by jnfrmarks** [comment]
The method name is remove_user_from_group, I put in the wrong name.

Here's the error I'm seeing:

2015-03-05 07:30:25,038 - CRITICAL - admin - Exception occured: HTTP/WebDAV error: 101: <message />

 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/jennifer/smashbox/lib/oc-tests/test_shareGroup.py", line 261, in admin
    removeUserFromGroup('user3', 'testgroup1')
  File "/home/jennifer/smashbox/python/smashbox/utilities/**init**.py", line 441, in removeUserFromGroup
    ocApi.remove_user_from_group (username, groupName)
  File "/home/jennifer/smashbox/python/smashbox/utilities/ownCloudWebDav.py", line 701, in remove_user_from_group
    self.__check_ocs_status(tree, [100, 102])
  File "/home/jennifer/smashbox/python/smashbox/utilities/ownCloudWebDav.py", line 1078, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP/WebDAV error: 101: <message />

```


The 101 return code is "group not found".

```

**Comment by jnfrmarks** [comment]
@PVince81 

Let me know when you have some time to help me out here.  Thanks!

**Comment by PVince81** [comment]
I just setup smashbox on another computer and ran the test "test_shareGroup.py" against v8.0.0 and master. There are no failures: https://s3.owncloud.com/owncloud/index.php/s/IIyB2j6TLedkHvj

My server uses mariadb 10.0, will try again with sqlite.

**Comment by PVince81** [comment]
I added some test results in that link.

I managed to reproduce some error cases, but they only happen if I start with a brand new empty ownCloud instance, and run "test_shareGroup.py" directly.
If I run another test like "test_basicSync.py" and then "test_shareGroup.py", then all run fine.

I suspect that "test_basicSync.py" might be setting up stuff (or leaving stuff) on the instance that make "test_shareGroup.py" work correctly.

When I run into errors, it looks like this: https://s3.owncloud.com/owncloud/index.php/s/xxdgWJk1KzpoxJ5

**Comment by PVince81** [comment]
Okay, tried this with a new instance:
1) Run "test_shareGroup.py": get strange errors
2) Run it again: same strange errors
3) Check "users" page in the instance: no test users
4) Run "test_basicSync.py": success
5) Check "users" page in the instance: three test users were created / left (I do have "delete" in the config for "oc_account_reset_procedure" and "rundir_reset_procedure")
6) Run "test_shareGroup.py" again: WORKS!

You might want to check whether "test_shareGroup.py" properly creates the test users.

**Comment by PVince81** [comment]
the last test was against stable8

**Comment by jnfrmarks** [comment]
@PVince81 @SergioBertolinSG 

I see this every time I run the test.

Sergio, can you run test_shareGroup.py and see if you also see a 101 error when removing the user from a group?  

I don't want to be ignoring a potential product issue here.

**Comment by SergioBertolinSG** [comment]
Yes, I've run that test against oc 8.0.1 with this error in step 14:

``````
********************************************************************************
(14) admin:  ADMIN USER REMOVES USER FROM GROUP
********************************************************************************
2015-03-12 07:35:47,098 - INFO - admin - Removing user user3 from group testgroup1
2015-03-12 07:35:47,569 - CRITICAL - admin - Exception occured: HTTP/WebDAV error: 101: <message />

 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/vagrant/SMASHBOX/smashbox/lib/oc-tests/test_shareGroup.py", line 261, in admin
    removeUserFromGroup('user3', 'testgroup1')
  File "/home/vagrant/SMASHBOX/smashbox/python/smashbox/utilities/__init__.py", line 463, in removeUserFromGroup
    ocApi.remove_user_from_group (username, groupName)
  File "/home/vagrant/SMASHBOX/smashbox/python/smashbox/utilities/ownCloudWebDav.py", line 701, in remove_user_from_group
    self.__check_ocs_status(tree, [100, 102])
  File "/home/vagrant/SMASHBOX/smashbox/python/smashbox/utilities/ownCloudWebDav.py", line 1078, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP/WebDAV error: 101: <message />```
``````

**Comment by PVince81** [comment]
Note: when I tested it was against the git version stable8 without EE apps. Are you testing against the enterprise daily build ?

**Comment by jnfrmarks** [comment]
Yes; I'm testing with enterprise builds.  I think that this is a product issue.

**Comment by PVince81** [comment]
Works for me with the owncloud-enterprise-complete build of 8.0.2: https://s3.owncloud.com/owncloud/index.php/s/alWQe8RJb8lj83f

Did you run "test_basicSync" first ? Please do, it will create the missing user/groups.
Running "test_shareGroup" directly will fail because of the missing prerequisites.

**Comment by jnfrmarks** [comment]
hmm, I get the same error (101 group not found) even when running test_basicSync first.  In fact, the test_shareGroup should not rely on any other test - if it did/does, then it's an error.

@PVince81  would you mind running against my server just to see if you can see the error then?  I can send you the info in IRC

**Comment by PVince81** [comment]
My setup:
- openSUSE 13.2 x86_64
- apache2-2.4.10-16.1.x86_64
- php5-5.6.1-8.1.x86_64

**Comment by PVince81** [comment]
I have setup a local Ubuntu 14.04 VM with owncloud-enterprise-complete-8.0.2 and am now seeing similar errors when running test_shareGroup:

```
2015-03-13 13:05:13,070 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_SHARE.dat should exist
2015-03-13 13:05:13,070 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_RESHARE.dat should exist
2015-03-13 13:05:13,070 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat should exist
2015-03-13 13:05:13,081 - ERROR - shareeTwo - /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat does not exist
2015-03-13 13:05:13,448 - ERROR - sharer - md5 of modified file /home/vincent/work/smashdir/test_shareGroup/sharer/TEST_FILE_MODIFIED_GROUP_SHARE.dat did not change: expected 45b565af28a2998fa8d5dae7eb6e660e, got 45b565af28a2998fa8d5dae7eb6e660e
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
2015-03-13 13:05:13,851 - ERROR - shareeOne - File /home/vincent/work/smashdir/test_shareGroup/shareeOne/TEST_FILE_GROUP_RESHARE.dat should exist
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
2015-03-13 13:05:15,233 - CRITICAL - admin - Exception occured: HTTP error: 101 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/vincent/work/workspace/smashbox/lib/oc-tests/test_shareGroup.py", line 261, in admin
    remove_user_from_group('user3', 'testgroup1')
  File "/home/vincent/work/workspace/smashbox/python/smashbox/utilities/__init__.py", line 605, in remove_user_from_group
    oc_api.remove_user_from_group(username, group_name)
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 785, in remove_user_from_group
    self.__check_ocs_status(tree, [100, 102])
  File "/home/vincent/work/workspace/pyocclient/owncloud/owncloud.py", line 1153, in __check_ocs_status
    raise ResponseError(r)
ResponseError: HTTP error: 101

2015-03-13 13:05:16,288 - ERROR - shareeOne - 1 error(s) reported
2015-03-13 13:05:16,288 - ERROR - sharer - 1 error(s) reported
2015-03-13 13:05:16,293 - ERROR - shareeTwo - 4 error(s) reported
CRITICAL:smash.:Aborting run -- non-zero exit code (1)
```

**Comment by PVince81** [comment]
I ran the same against owncloud-8.0.2 on the same Ubuntu machine after running test_basicSync (to get the missing initial users) and I only get test-related fails (not API):

```
2015-03-13 13:14:06,077 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_SHARE.dat should exist
2015-03-13 13:14:06,078 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_GROUP_RESHARE.dat should exist
2015-03-13 13:14:06,078 - ERROR - shareeTwo - File /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat should exist
2015-03-13 13:14:06,170 - ERROR - shareeTwo - /home/vincent/work/smashdir/test_shareGroup/shareeTwo/TEST_FILE_MODIFIED_GROUP_SHARE.dat does not exist
2015-03-13 13:14:06,511 - ERROR - sharer - md5 of modified file /home/vincent/work/smashdir/test_shareGroup/sharer/TEST_FILE_MODIFIED_GROUP_SHARE.dat did not change: expected 45b565af28a2998fa8d5dae7eb6e660e, got 45b565af28a2998fa8d5dae7eb6e660e
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
2015-03-13 13:14:06,912 - ERROR - shareeOne - File /home/vincent/work/smashdir/test_shareGroup/shareeOne/TEST_FILE_GROUP_RESHARE.dat should exist
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): test-ubuntuserver3.local
2015-03-13 13:14:09,237 - ERROR - shareeTwo - 4 error(s) reported
2015-03-13 13:14:09,237 - ERROR - sharer - 1 error(s) reported
2015-03-13 13:14:09,245 - ERROR - shareeOne - 1 error(s) reported
```

So basically, the "CRITICAL - admin - Exception occured: HTTP error: 101" only happens in the EE version (on Ubuntu 14.04, not openSUSE), additionally to the other test expectation errors.

**Comment by PVince81** [comment]
If you disable the "Firewall" app, the 101 error disappear and the result is the same as in CE 8.0.2.

I tried applying @th3fallen's patch https://github.com/owncloud/firewall/pull/81 but unfortunately it doesn't resolve this issue.

**Comment by jnfrmarks** [comment]
bug filed: https://github.com/owncloud/firewall/issues/82

**Comment by nickvergessen** [comment]
`lib/oc-tests/test_shareGroup.py` works since https://github.com/owncloud/smashbox/pull/73/files

Feel free to create a new issue, if it's still failing for you.
