### ISSUE TITLE
exceptions raised inside smashbox makes the script to get stuck

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/smashbox#39]
pyocclient isn't found raising an error. The bin/smash executable get stuck in this case

```
SUMMARY:smash.:oc_server: localhost:10080
SUMMARY:smash.:oc_ssl_enabled: False
SUMMARY:smash.:runid: 150323-122536
SUMMARY:smash.:running /home/usertest/smashbox/lib/test_basicSync.py in /home/usertest/smashdir/test_basicSync as user testset #0 None
2015-03-23 12:25:37,069 - CRITICAL - creator - Exception occured: No module named owncloud 
 Traceback (most recent call last):
  File "/home/usertest/smashbox/python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/usertest/smashbox/lib/test_basicSync.py", line 98, in creator
    reset_owncloud_account()
  File "/home/usertest/smashbox/python/smashbox/utilities/__init__.py", line 41, in reset_owncloud_account
    delete_owncloud_account(username)
  File "/home/usertest/smashbox/python/smashbox/utilities/__init__.py", line 118, in delete_owncloud_account
    oc_api = get_oc_api()
  File "/home/usertest/smashbox/python/smashbox/utilities/__init__.py", line 507, in get_oc_api
    import owncloud
ImportError: No module named owncloud
```

The script should exit, not get stuck. It's needed to use forcefully exit the script (using control+c or killing the process)

**Comment by jvillafanez** [comment]
It probably get blocked in https://github.com/owncloud/smashbox/blob/master/python/smashbox/multiprocessing_engine.py#L119

The root cause might be in https://github.com/owncloud/smashbox/blob/master/python/smashbox/multiprocessing_engine.py#L161
One of the workers exits abruptly, but the rest of the workers still wait for the process to finish the step to continue working.

NOTICE: This gives a possible explanation of what could be happening, but it could be wrong.

**Comment by jvillafanez** [comment]
Adding logs:

log-test_uploadFiles.log

```
2015-03-27 13:43:03,769 - INFO - None - BEGIN SMASH RUN - rundir: /root/smashdir/test_uploadFiles
2015-03-27 13:43:03,921 - INFO - setup - entering new step 
********************************************************************************
(1) setup:  CREATE TEST USERS
********************************************************************************
2015-03-27 13:43:03,921 - INFO - setup - reset_owncloud_account (delete) for 3 users
2015-03-27 13:43:03,921 - INFO - setup - Deleting user user1
2015-03-27 13:43:04,158 - CRITICAL - setup - Exception occured: No module named wtf 
 Traceback (most recent call last):
  File "/root/smashbox/python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/root/smashbox/lib/oc-tests/test_uploadFiles.py", line 73, in setup
    reset_owncloud_account(num_test_users=config.oc_number_test_users)
  File "/root/smashbox/python/smashbox/utilities/__init__.py", line 46, in reset_owncloud_account
    delete_owncloud_account(username)
  File "/root/smashbox/python/smashbox/utilities/__init__.py", line 123, in delete_owncloud_account
    oc_api = get_oc_api()
  File "/root/smashbox/python/smashbox/utilities/__init__.py", line 528, in get_oc_api
    import wtf
ImportError: No module named wtf

2015-03-27 13:43:04,167 - INFO - shareeTwo - entering new step 
********************************************************************************
(2) shareeTwo:  SHAREE TWO CREATES WORKDIR
********************************************************************************
2015-03-27 13:43:04,167 - INFO - shareeTwo - running 'mkdir -p /root/smashdir/test_uploadFiles/shareeTwo'
2015-03-27 13:43:04,168 - INFO - sharer - entering new step 
********************************************************************************
(2) sharer:  CREATE WORKDIR
********************************************************************************
2015-03-27 13:43:04,168 - INFO - sharer - running 'mkdir -p /root/smashdir/test_uploadFiles/sharer'
2015-03-27 13:43:04,169 - INFO - shareeOne - entering new step 
********************************************************************************
(2) shareeOne:  SHAREE ONE CREATES WORKDIR
********************************************************************************
2015-03-27 13:43:04,169 - INFO - shareeOne - running 'mkdir -p /root/smashdir/test_uploadFiles/shareeOne'
2015-03-27 13:43:04,193 - INFO - shareeOne - make_workdir /root/smashdir/test_uploadFiles/shareeOne
2015-03-27 13:43:04,194 - INFO - sharer - make_workdir /root/smashdir/test_uploadFiles/sharer
2015-03-27 13:43:04,196 - INFO - shareeTwo - make_workdir /root/smashdir/test_uploadFiles/shareeTwo
2015-03-27 13:43:04,196 - INFO - shareeTwo - running 'mkdir -p /root/smashdir/test_uploadFiles/shareeTwo/localShareDir'
2015-03-27 13:43:04,214 - INFO - shareeTwo - make_workdir /root/smashdir/test_uploadFiles/shareeTwo/localShareDir
2015-03-27 13:43:04,226 - INFO - sharer - entering new step 
********************************************************************************
(3) sharer:  CREATE INITIAL TEST DIRECTORY
********************************************************************************
2015-03-27 13:43:04,226 - INFO - sharer - running 'mkdir -p /root/smashdir/test_uploadFiles/sharer/localShareDir'
2015-03-27 13:43:04,237 - INFO - sharer - make_workdir /root/smashdir/test_uploadFiles/sharer/localShareDir
2015-03-27 13:43:04,237 - INFO - sharer - running 'ls -lh /root/smashdir/test_uploadFiles/sharer'
2015-03-27 13:43:04,241 - INFO - sharer - stdout: total 1.7M
drwxr-xr-x 2 root root 4.0K Mar 27 09:31 Documents
drwxr-xr-x 2 root root 4.0K Mar 27 09:31 Photos
drwxr-xr-x 2 root root 4.0K Mar 27 09:31 localShareDir
-rw-r--r-- 1 root root 1.7M Mar 27 09:31 ownCloudUserManual.pdf

2015-03-27 13:43:04,241 - INFO - sharer - running '/usr/bin/owncloudcmd /root/smashdir/test_uploadFiles/sharer/ owncloud://user1:demo@172.17.0.32/remote.php/webdav/ >> /root/smashdir/test_uploadFiles/sharer-ocsync.step03.cnt000.log 2>&1'
```

test_uploadFiles/sharer-ocsync.step03.cnt000.log

```
03-27 13:43:05:249 _csync_detect_update: file: ownCloudUserManual.pdf, instruction: INSTRUCTION_NONE <<=
03-27 13:43:05:249 csync_ftw:  <= Closing walk for /root/smashdir/test_uploadFiles/sharer with read_from_db 0
03-27 13:43:05:249 csync_update: Update detection for local replica took 0.03 seconds walking 9 files.
03-27 13:43:05:249 csync_memstat_check: Memory: 244044K total size, 16056K resident, 12492K shared
03-27 13:43:05:249 oc_module: opendir method called on owncloud://user1:demo@172.17.0.32/remote.php/webdav
03-27 13:43:05:249 oc_module: * scheme owncloud
03-27 13:43:05:249 oc_module: * host 172.17.0.32
03-27 13:43:05:249 oc_module: * port 0
03-27 13:43:05:249 oc_module: * path /remote.php/webdav
03-27 13:43:05:249 oc_module: * user user1
03-27 13:43:05:249 oc_module: fetch_resource_list_recursive Starting recursive propfind owncloud://user1:demo@172.17.0.32/remote.php/webdav /remote.php/webdav
03-27 13:43:05:414 oc_module:  Set-Cookie found: oc9nhgvb06sk=hphuutlqlpag40vdsfr5du08p4; path=/; HttpOnly
03-27 13:43:05:414 oc_module: ----> Session-key: oc9nhgvb06sk=hphuutlqlpag40vdsfr5du08p4
03-27 13:43:05:414 oc_module: Authentication required 
03-27 13:43:05:466 oc_module: Authentication required user1
03-27 13:43:05:466 oc_module: Neon error code was 3
03-27 13:43:05:466 oc_module: WRN: propfind named failed with 3, request error: Could not authenticate to server: rejected Basic challenge
03-27 13:43:05:466 oc_module: fill_recursive_propfind_cache /remote.php/webdav Server maybe did not give us an 'infinity' depth result
03-27 13:43:05:466 oc_module: get_listdir_context_from_recursive_cache No cache
03-27 13:43:05:509 oc_module: Authentication required user1
03-27 13:43:05:556 oc_module: Authentication required user1
03-27 13:43:05:556 oc_module: Neon error code was 3
03-27 13:43:05:556 oc_module: Neon error code was 3
03-27 13:43:05:556 oc_module: WRN: propfind named failed with 3, request error: Could not authenticate to server: rejected Basic challenge
03-27 13:43:05:556 oc_module: Errno set to 10004
03-27 13:43:05:556 csync_ftw: opendir failed for owncloud://user1:demo@172.17.0.32/remote.php/webdav - Unknown error 10004 (errno 10004)
03-27 13:43:05:556  #### ERROR during  csync_update :  "CSync failed to authenticate at the ownCloud server. Could not authenticate to server: rejected Basic challenge" 
```

**Comment by labkode** [comment]
For me this exception is raised  due the fact that owncloud module (https://github.com/owncloud/pyocclient) is not found.
If you open a python shell and do `import owncloud` you will get the same error.
I tried `pip install pyocclient` several times and I am still facing this error.
Maybe the python egg is not well configured.

**Comment by jvillafanez** [comment]
@labkode It's fine that smashbox crashes in that event, I would expect that, but the problem is that smashbox gets stuck and the script doesn't finish.

I can't say for sure if this is the only case where smashbox gets stuck or not

**Comment by nickvergessen** [comment]
Works for me, it always terminates (some times a bit later after trying several steps)
So I'm closing this. Also if it is still happening, report it to https://github.com/cernbox/smashbox please
