### ISSUE TITLE
Installation steps

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/smashbox#43]
Following steps are done locally:

```
mkvirtualenv smashbox -p /usr/bin/python2
mkdir ~/smashbox
vim etc/smashbox.conf.templates 
    oc_account_password <- random password
    oc_server <- IP address
    oc_root <- subfolder
    oc_ssl_enabled <- if no SSL is used
    oc_sync_cmd <- adjust path to owncloudcmd
    oc_admin_user <- admin user
    oc_admin_password <- admin password

smoke test:
    bin/smash lib/test_basicSync.py
```

mkvirtualenv is a zsh extension, which uses virtualenvwrapper to create a virtual env to have an isolated python env.

cc @PVince81 @jnfrmarks Maybe improve the readme with this info.

**Comment by jospoortvliet** [comment]
Are you saying smashbox needs python 2.7 rather than 3.4? I've got quite some error messages here, starting with this:

```
2015-06-17 21:29:49,100 - CRITICAL - creator - Exception occured: Client instance has no attribute 'delete_user' 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/jospoortvliet/smashbox/lib/test_basicSync.py", line 98, in creator
    reset_owncloud_account()
  File "/home/jospoortvliet/smashbox/python/smashbox/utilities/__init__.py", line 40, in reset_owncloud_account
    delete_owncloud_account(config.oc_account_name)
  File "/home/jospoortvliet/smashbox/python/smashbox/utilities/__init__.py", line 144, in delete_owncloud_account
    oc_api.delete_user(username)
AttributeError: Client instance has no attribute 'delete_user'
```

Is that related or am I just doing something wrong...

**Comment by jnfrmarks** [comment]
Yes, smashbox uses 2.7 and does not yet support 3.4

And, you need to install pyocclient:

pip install -r requirements.txt

**Comment by jospoortvliet** [comment]
yeah, I did that, but it looks like debian has 3.4 as default so everything got installed there and I get loads of errors
I'll have to move to 2.7 then.
edit - my mistake, this was on openSUSE and indeed pip3 was installed, not pip2. installed now, fresh errors so at least some progress

**Comment by jospoortvliet** [comment]
That seemed to have helped at least a little, yes - I get a nice 401 now:

```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 10.42.0.152
2015-06-17 22:26:10,217 - CRITICAL - creator - Exception occured: HTTP error: 401 
 Traceback (most recent call last):
  File "python/smashbox/multiprocessing_engine.py", line 161, in worker_wrap
    f(step)
  File "/home/jospoortvliet/smashbox/lib/test_basicSync.py", line 98, in creator
    reset_owncloud_account()
  File "/home/jospoortvliet/smashbox/python/smashbox/utilities/__init__.py", line 40, in reset_owncloud_account
    delete_owncloud_account(config.oc_account_name)
  File "/home/jospoortvliet/smashbox/python/smashbox/utilities/__init__.py", line 144, in delete_owncloud_account
    oc_api.delete_user(username)
  File "/home/jospoortvliet/smashbox/src/pyocclient/owncloud/owncloud.py", line 729, in delete_user
    raise ResponseError(res)
ResponseError: HTTP error: 401
```

sorry for abusing this bugreport...

**Comment by jospoortvliet** [comment]
/me goes change the readme to at least mention the python thing
